services:
  servicehub:
    build: .
    container_name: servicehub
    ports:
      - "5055:5000"
    volumes:
      - .:/app
      - ./data:/data
    environment:
      - TZ=Europe/Helsinki
    restart: unless-stopped    